
const Discord = require('discord.js');
const Twana1 = new Discord.Client();
const Twana2 = new Discord.Client();
const Twana3 = new Discord.Client();
const Twana4 = new Discord.Client();
const Twana5 = new Discord.Client();
const Twana6 = new Discord.Client();
const Twana7 = new Discord.Client();
const Twana8 = new Discord.Client();
const Twana9 = new Discord.Client();
const Twana10 = new Discord.Client();
const Twana11 = new Discord.Client();
const Twana12 = new Discord.Client();
const Twana13 = new Discord.Client();
const Twana14 = new Discord.Client();
const Twana15 = new Discord.Client();
const Twana16 = new Discord.Client();
const Twana17 = new Discord.Client();
const Twana18 = new Discord.Client();
const Twana19 = new Discord.Client();
const Twana20 = new Discord.Client();
const Twana21 = new Discord.Client();
const Twana22 = new Discord.Client();
const Twana23 = new Discord.Client();
const Twana24 = new Discord.Client();
const Twana25 = new Discord.Client();
const Twana26 = new Discord.Client();
const Twana27 = new Discord.Client();
const Twana28 = new Discord.Client();
const Twana29 = new Discord.Client();
const Twana30 = new Discord.Client();
const Twana31 = new Discord.Client();
const Twana32 = new Discord.Client();
const Twana33 = new Discord.Client();
const Twana34 = new Discord.Client();
const Twana35 = new Discord.Client();
const Twana36 = new Discord.Client();
const Twana37 = new Discord.Client();
const Twana38 = new Discord.Client();
const Twana39 = new Discord.Client();
const Twana40 = new Discord.Client();
const Twana41 = new Discord.Client();
const Twana42 = new Discord.Client();
const Twana43 = new Discord.Client();
const Twana44 = new Discord.Client();
const Twana45 = new Discord.Client();
const Twana46 = new Discord.Client();
const Twana47 = new Discord.Client();
const Twana48 = new Discord.Client();
const Twana49 = new Discord.Client();
const Twana50 = new Discord.Client();
const Twana51 = new Discord.Client();
const Twana52 = new Discord.Client();
const Twana53 = new Discord.Client();
const Twana54 = new Discord.Client();
const Twana55 = new Discord.Client();
const Twana56 = new Discord.Client();
const Twana57 = new Discord.Client();
const Twana58 = new Discord.Client();
const Twana59 = new Discord.Client();
const Twana60 = new Discord.Client();
const Twana61 = new Discord.Client();
const Twana62 = new Discord.Client();
const Twana63 = new Discord.Client();
const Twana64 = new Discord.Client();
const Twana65 = new Discord.Client();
const Twana66 = new Discord.Client();
const Twana67 = new Discord.Client();
const Twana68 = new Discord.Client();
const Twana69 = new Discord.Client();
const Twana70 = new Discord.Client();
const Twana71 = new Discord.Client();
const Twana72 = new Discord.Client();
const Twana73 = new Discord.Client();
const Twana74 = new Discord.Client();
const Twana75 = new Discord.Client();
const Twana76 = new Discord.Client();
const Twana77 = new Discord.Client();
const Twana78 = new Discord.Client();
const Twana79 = new Discord.Client();
const Twana80 = new Discord.Client();
const Twana81 = new Discord.Client();
const Twana82 = new Discord.Client();
const Twana83 = new Discord.Client();
const Twana84 = new Discord.Client();
const Twana85 = new Discord.Client();
const Twana86 = new Discord.Client();
const Twana87 = new Discord.Client();
const Twana88 = new Discord.Client();
const Twana89 = new Discord.Client();
const Twana90 = new Discord.Client();
const Twana91 = new Discord.Client();
const Twana92 = new Discord.Client();
const Twana93 = new Discord.Client();
const Twana94 = new Discord.Client();
const Twana95 = new Discord.Client();
const Twana96 = new Discord.Client();
const Twana97 = new Discord.Client();
const Twana98 = new Discord.Client();
const Twana99 = new Discord.Client();
const Twana100= new Discord.Client();



Twana1.login("ODE0OTQzNDMwMTE0NDEwNDk2.YDlNsg.fXshyhPMhkKk41SPm2cXHteQXI0");
Twana2.login("ODE0OTQyODIwNzQxODA4MTM5.YDlNHQ.I9qy0D8hqHCOrV-Q3j4Fdu6Ab_o");
Twana3.login("ODE0OTU3MDcyMjI3MjM3OTI4.YDlbIg.TNevspTYgXsUI4_CtZBljg3UoWc");
Twana4.login("ODE0OTU4MzUyMjIzMzA1NzQ5.YDlbpg.k_A4Q0xB-Byve1EKuiM5EXkcTF0");
Twana5.login("ODE0OTU4OTE1NDc2OTE0MTg2.YDlcLg.JBj4c6mZvsekxPYC-KqUhKMnTuA");
Twana6.login("ODE0OTU5MzY1MDYwMjk2NzI0.YDlcmw.OzZ_KNwKSkKJnjP1csF5JYQl-a4");
Twana7.login("ODE0OTU5OTM1NzcwMDY3MDE0.YDldLw.5Qxy3p3zZVR6EK0pdwEI4D1u8JQ");
Twana8.login("ODE0OTYwNTU0MzI1NDQyNTcw.YDldzw.oZdKorc2B8LnKFs815f30GwgiEU");
Twana9.login("ODE0OTYxMjMwMjQxNTk1NDAy.YDleTg.gypEQoEKQ28JJttbkpSvFDvnZk4");
Twana10.login("ODE0OTYxNzUxOTU1MjEwMzEx.YDlfUA.jtJaF2UW3s0eN4wMzpq4Epkz7aQ");
Twana11.login("ODE0OTYyNzMyODIxOTA1NDM5.YDlftw.xPs08-7pd2feF6OhTtTAMr0-_a8");
Twana12.login("ODE0OTYzNzM0NDY3MzEzNjc1.YDlgbQ.QpeQyRBX7iQSPt1f5vZL3k1x_iw");
Twana13.login("ODE0OTYzODcyMjcyMzUxMjcy.YDlg0A.rTUTqjPHZPHmXC_Gw8EnUZPeWiY");
Twana14.login("ODE0OTY0NDU3NjQ2MDYzNjkx.YDlhZw.fXZ6Yh2XoLrQDYgfcb7fQAu9MtA");
Twana15.login("ODE0OTY1MDAyMjcxODUwNTY2.YDlhyA.3S_OHdbjRwg_nIEeFEoHJpM9hY4");
Twana16.login("ODE0OTY1NDY5Njg5Njc1ODA3.YDliWg.CQoRClFa0AlAcBOSTEUOS7cJUm4");
Twana17.login("ODE0OTY2MDM2OTUyNTE0NjIx.YDli3A.DAhx5xqqo6oclqv28fhV4tSH_08");
Twana18.login("ODE0OTY2NTY3NTAyMDg2MjA0.YDljKg.vQqbEfytzPVN-oYYZMYTEHhVMv0");
Twana19.login("ODE0OTY2OTg0MDAwNjY3NjY5.YDljqg.1h9nPBAB-koIB53XN7P0S-i9ufY");
Twana20.login("ODE0OTY3NTIwOTc2OTYxNTk3.YDlkMw.GNlFJ9majvxT5XhuhYE7PAv__bQ");
Twana21.login("ODE0OTY4MDkzNTI0MDk5MTEy.YDlkrA.fcLZhmXRqKRCkh6K9RtNLqoBa1M");
Twana22.login("ODE0OTY4NTk4MDIzMzcyODMw.YDllPA.h0V2EH2dZSWpRs5YeBMWQCNAiLY");
Twana23.login("ODE0OTY5MjA2NTExNzYzNDk2.YDll3g.wqQ_c-Ae7gTt5X_xo-DsTBFb9Qg");
Twana24.login("ODE0OTY5ODgyOTkwNzM5NDc2.YDlmWQ.OzYdtRlqQSfnGA6V6bXUO30DUs8");
Twana25.login("ODE0OTcwMzE3NDAzNDU1NTQ4.YDlmwA.oo0unkfoDYcdCm8RNH01jncOvnU");
Twana26.login("ODE0OTcwNzM0MTg2MjAxMTI5.YDlnMA.o94eUrR6SGGpPwPql-0tt0oVjF0");
Twana27.login("ODE0OTcxMzA3MDMyNzA3MTIy.YDlntA.7zWmb6li92L0vferf5QEHZafpsk");
Twana28.login("ODE0OTcxODU0MDM1ODc3ODg4.YDlocA.W1WSugoSs098UKJ5BQk00xyY4wM");
Twana29.login("ODE0OTcyNjQyODYzMDg3NjI3.YDlopg.e4MmQlTIuO_SPTd6JWJ8-vP7H1E");
Twana30.login("ODE0OTczMjI3Mjc2Njk3NjMy.YDlpSw.VjZdnDu66EfqWzxT9gmPwLcywIc");
Twana31.login("ODE0OTczNTYzMjE1NDEzMzIw.YDlpvg.hoaZX3Po7uqJacLPWgoMwb8gZKo");
Twana32.login("ODE0OTc0MDQ0ODAwODExMDE4.YDlqOA.p2A_Hl-g2Lm9lN5uEtb6q8fjDjY");
Twana33.login("ODE0OTc0NTQxNTQwNjIyMzk4.YDlqqg.sJikYJxvgmbWBxnOtExT32Qn95E");
Twana34.login("ODE0OTc1MDM5NzY5NDExNjU1.YDlrUA.yZAWNEJyjrpGvSn7wklbVB6qQJg");
Twana35.login("ODE0OTc1NzAzNTAxNTA0NTMy.YDlrxg._P8Un4iffYOMWayexS8NGdrIGP8");
Twana36.login("ODE0OTc2MjI5MjIzNTYzMjY0.YDlsjQ.lRuEEBzme1jIiGYbzy3gSUYARNQ");
Twana37.login("ODE0OTc3MDY0MzE4MTQwNDM3.YDltcw.zo3TBLU7eQyxXDqUKfBl5zDvTf4");
Twana38.login("ODE0OTc3OTQyNTAwMTQ3MjMy.YDlt_A.pi6dFyni5XJScHIyxb1ePVJ1xIA");
Twana39.login("ODE0OTc4NDc2OTMxMTUzOTQw.YDluTQ.T60joVHfk5SFRtNYpCf2Jgv53cI");
Twana40.login("ODE0OTc4OTQ1MDk0NjQ3ODQ4.YDluwA.nT9M3HW7tqldOCFRltL2tCvsn_E");
Twana41.login("ODE0OTc5NDE4NjkzOTU5NzMx.YDlvQg.fUFjYWQu-SpciTxiMS31R39hPz0");
Twana42.login("ODE0OTc5OTYzMjkwNjQ4NTg2.YDlv0A.nM2w_MmlDM3o6BUr7hz2E93_cRQ");
Twana43.login("ODE0OTgwNTY3Nzg3MTEwNDMw.YDlwlQ.028N2B953nuF6QxoXOStxitPmJw");
Twana44.login("ODE0OTgxMjk2Mzc1MjAxODUy.YDlwpw.m34CBrIbkcx2EOJmpKl_Llvkc7Y");
Twana45.login("ODE0OTgxMjk2Mzc1MjAxODUy.YDlxPA.rB9vdo1xhD0Hy_20vV0FY6MfH6E");
Twana46.login("ODE0OTgxOTc2Mzc2NDc1Njk4.YDlxTg.NM_zYso4BtIF4dqy817K-62zyHQ");
Twana47.login("ODE0OTgyNDA4MTM4MjYwNTMw.YDlydA.p-UbeTNBTPAjv_23WiYMqajV78o");
Twana48.login("ODE0OTgzMjY1NDI1NDI0Mzg2.YDlygQ.B2dqutDvnLSUtoXnzaYHRTrcmk4");
Twana49.login("ODE0OTgzNzA4NDk0MDA0MjU0.YDlzHA.QDzNlU-qtuGEMJe2-RAi7LPhyKg");
Twana50.login("ODE0OTg0MTA4MTE1NDkyODY0.YDlz1w.KMTBe17WqUtaHYFyf1-LzZ8ki5I");
Twana51.login("ODE0OTg0NzEwOTc1MTI3NTUy.YDl0Pw.nED7faRtEIjtJ5c_jvp09hICp3Y");
Twana52.login("ODE0OTg1MzA4OTg1NjIyNTM4.YDl09A.8yXkGkIKGbSrUouH8RGK8Neoudw");
Twana53.login("ODE0OTg2MDg3NDg2OTgwMTM3.YDl1bg.5oJHF9FWmgnrSvcpnJNM7Bu3nwA");
Twana54.login("ODE0OTg2NTkyNTA1NTYxMTE4.YDl2fA.OnKvaSj37kRUM-Z88udSLf4dN20");
Twana55.login("ODE0OTg3NzI3NzQ0Nzk0NzA2.YDl3Aw.jnamT070dSSqpRCw0dFiEdoRFaI");
Twana56.login("ODE0OTg4MjkwNjk2MTUxMDUw.YDl3hA.gan13tuYjnp9kSLGsuG6YSooOr0");
Twana57.login("ODE0OTg4ODM0MTUxODU4MjQ2.YDl4BQ.lFxDWUwh55t6heEn-h7NaycJhog");
Twana58.login("ODE0OTg5MzcxNTkzNDU3Njk0.YDl4YA.quweV5nCiIqtJZRywwNHXjRjQ9c");
Twana59.login("ODE0OTg5NzU5OTYwODQyMjgx.YDl5CA.PivN9UMonaSk9FcvuKwnc6FQwLE");
Twana60.login("ODE0OTkwMzUyMzM1MTEwMTQ0.YDl5fA.AhXJYUfbHDvmcA-V3bPv_wYHCjY");
Twana61.login("ODE0OTkwODY5NTUxMTIwMzg0.YDl54Q.5bMsTHIXwASihOfMxrluyO_pGqk");
Twana62.login("ODE0OTkxMzY5NDMyMDcyMTky.YDl6ZQ.A_inLbonaJJIpo4p6QV4PDV-iGw");
Twana63.login("ODE0OTkxOTMwNjg0OTk3Njky.YDl6xQ.jZUGWb_VznIqk0mJayGQGYco3vI");
Twana64.login("ODE0OTkyMzE3MDM4ODU0MTg1.YDl7oA.Ln1nZC7t0hTttGaAtMWm3GER18s");
Twana65.login("ODE0OTkzMDE1MDg0MTU0ODkx.YDl73Q.bNn_4y0FDeF1Eqm2C_yTwLPBNoA");
Twana66.login("ODE0OTkzNTAwMTA5NDA2MjQw.YDl8YQ.cHtHrAGbJAEnmvqkG1YXCrdR158");
Twana67.login("ODE0OTk0MDU4MTE5NzQxNDUw.YDl85A.xD8ItfxTGf-YeB8-GN2V9pcKmuU");
Twana68.login("ODE0OTk0NTkwOTg0Njk5OTM0.YDl90A.2L_3f_m2MzPOiuENc1O1R0Gj5AU");
Twana69.login("");
Twana70.login("");
Twana71.login("");
Twana72.login("");
Twana73.login("");
Twana74.login("");
Twana75.login("");
Twana76.login("");
Twana77.login("");
Twana78.login("");
Twana79.login("");
Twana80.login("");
Twana81.login("");
Twana82.login("");
Twana83.login("");
Twana84.login("");
Twana85.login("");
Twana86.login("");
Twana87.login("");
Twana88.login("");
Twana89.login("");
Twana90.login("");
Twana91.login("");
Twana92.login("");
Twana94.login("");
Twana95.login("");
Twana96.login("");
Twana97.login("");
Twana98.login("");
Twana99.login("");
Twana100.login("");









